import os
import io
import random
import logging
from datetime import datetime
import uuid

import numpy as np
import torch
import librosa
import soundfile as sf
import ffmpeg
import imageio_ffmpeg

from fastapi import FastAPI, File, UploadFile, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
import uvicorn
from dotenv import load_dotenv
from bson import ObjectId

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm

# ================= LOAD ENV =================
load_dotenv()

# ================= PROJECT IMPORTS =================
from database import history_collection
from auth import router as auth_router, get_current_user
from contact import router as contact_router
from model_loader import load_model_robust

# ================= LOGGING =================
logger = logging.getLogger("stutter-api")
logging.basicConfig(level=logging.INFO)

# ================= MODEL LOAD =================
MODEL_PATH = os.environ.get("MODEL_PATH", "./models/model_epoch10.pth")
DEVICE = os.environ.get("DEVICE", "cpu")

logger.info(f"Loading model from: {MODEL_PATH}")
model = load_model_robust(MODEL_PATH, device=DEVICE)

if model is not None:
    model.eval()
    logger.info("MODEL LOADED SUCCESSFULLY")
else:
    logger.warning("Model not loaded – fallback mode enabled")

# ================= FASTAPI APP =================
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ================= ROUTERS =================
app.include_router(auth_router, prefix="/auth", tags=["auth"])
app.include_router(contact_router, tags=["contact"])

# ================= AUDIO CONFIG =================
SR = 16000
TARGET_LEN = 24000
N_MELS = 64
N_FFT = 1024
HOP_LEN = 256

# ================= AUDIO DECODER =================
def audio_bytes_to_np(raw: bytes):
    if not raw or len(raw) < 10:
        raise HTTPException(status_code=400, detail="Empty audio")

    try:
        y, sr = sf.read(io.BytesIO(raw), dtype="float32")
        if y.ndim > 1:
            y = np.mean(y, axis=1)
        if sr != SR:
            y = librosa.resample(y, sr, SR)
        return y
    except Exception:
        pass

    try:
        ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
        out, _ = (
            ffmpeg.input("pipe:", loglevel="quiet")
            .output("pipe:", format="wav", acodec="pcm_s16le", ac=1, ar=str(SR))
            .run(
                input=raw,
                capture_stdout=True,
                capture_stderr=True,
                cmd=ffmpeg_exe,
            )
        )
        y, _ = sf.read(io.BytesIO(out), dtype="float32")
        return y
    except Exception:
        raise HTTPException(status_code=400, detail="Unsupported audio format")

# ================= HELPERS =================
def ensure_length(y):
    if len(y) < TARGET_LEN:
        return np.pad(y, (0, TARGET_LEN - len(y)))
    return y[:TARGET_LEN]

def mel_from_wave(y):
    y = ensure_length(y)
    mel = librosa.feature.melspectrogram(
        y=y,
        sr=SR,
        n_mels=N_MELS,
        n_fft=N_FFT,
        hop_length=HOP_LEN,
    )
    mel_db = librosa.power_to_db(mel, ref=np.max)
    return mel_db.astype(np.float32)

# ================= PDF GENERATOR =================
def generate_pdf_report(result: dict, filepath: str):
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4
    y = height - 2 * cm

    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, y, "FLUENCY ASSIST – ANALYSIS REPORT")

    y -= 1.5 * cm
    c.setFont("Helvetica", 11)
    c.drawString(2 * cm, y, f"Email: {result['email']}")
    y -= 0.6 * cm
    c.drawString(2 * cm, y, f"File: {result['filename']}")
    y -= 0.6 * cm
    c.drawString(2 * cm, y, f"Date: {result['timestamp']}")

    y -= 1.2 * cm
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2 * cm, y, "Result Summary")

    y -= 0.8 * cm
    c.setFont("Helvetica", 12)
    c.drawString(2 * cm, y, f"Status: {result['status']}")
    y -= 0.6 * cm
    c.drawString(2 * cm, y, f"Confidence: {result['confidence']}%")

    y -= 1 * cm
    c.setFont("Helvetica-Bold", 13)
    c.drawString(2 * cm, y, "Speech Breakdown (%)")

    y -= 0.7 * cm
    c.setFont("Helvetica", 11)
    for k, v in result["breakdown"].items():
        c.drawString(2.5 * cm, y, f"{k.capitalize()}: {v}%")
        y -= 0.5 * cm

    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, 1.5 * cm, "Generated by Fluency Assist")
    c.showPage()
    c.save()

ALLOWED_AUDIO_TYPES = {
    "audio/wav", "audio/wave", "audio/x-wav",
    "audio/mpeg", "audio/mp3", "audio/ogg",
    "audio/webm", "audio/flac", "audio/x-flac",
    "video/webm", "application/octet-stream", "",
}

def is_valid_audio(raw: bytes) -> bool:
    """Check magic bytes to detect real audio formats."""
    if len(raw) < 4:
        return False
    # RIFF/WAV
    if raw[:4] == b'RIFF':
        return True
    # MP3 (ID3 tag or sync bytes)
    if raw[:3] == b'ID3' or raw[:2] in (b'\xff\xfb', b'\xff\xf3', b'\xff\xf2'):
        return True
    # OGG
    if raw[:4] == b'OggS':
        return True
    # FLAC
    if raw[:4] == b'fLaC':
        return True
    # WebM / MKV (EBML header)
    if raw[:4] == b'\x1a\x45\xdf\xa3':
        return True
    # MP4/M4A
    if raw[4:8] in (b'ftyp', b'moov', b'mdat'):
        return True
    return False

# ================= HEALTH =================
@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": model is not None}

# ================= PREDICT =================
@app.post("/predict")
async def predict_audio(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user),
):
    raw = await file.read()
    if not is_valid_audio(raw):
        raise HTTPException(status_code=400, detail="Unsupported or invalid audio file")
    logger.info(f"Received file: {file.filename}, size={len(raw)} bytes")

    y = audio_bytes_to_np(raw)
    mel = mel_from_wave(y)

    logger.info(f"Audio samples={len(y)}, mel mean={mel.mean():.4f}, std={mel.std():.4f}")

    mel_tensor = torch.tensor(mel).unsqueeze(0).unsqueeze(0)

    # -------- MODEL INFERENCE --------
    if model is None:
        prob = random.uniform(0.4, 0.9)
    else:
        with torch.no_grad():
            out = model(mel_tensor)
            logger.info(f"Model raw output: {out}")

            if out.shape[1] == 1:
                prob = torch.sigmoid(out)[0][0].item()
            else:
                prob = torch.softmax(out, dim=1)[0][1].item()

    conf = round(prob * 100, 2)
    label = "Stuttering Detected" if prob > 0.5 else "Normal Speech"

    # -------- DYNAMIC BREAKDOWN --------
    if label == "Stuttering Detected":
        rep = round(conf * 0.4)
        prog = round(conf * 0.35)
        blk = round(conf * 0.25)
        normal = max(0, 100 - (rep + prog + blk))

        breakdown = {
            "normal": normal,
            "repetition": rep,
            "prolongation": prog,
            "block": blk,
        }
        details = "Stuttering patterns detected in speech."
    else:
        breakdown = {
            "normal": 100,
            "repetition": 0,
            "prolongation": 0,
            "block": 0,
        }
        details = "Speech appears normal."

    # -------- STORE RESULT --------
    doc = {
        "email": current_user["email"],
        "filename": file.filename,
        "status": label,
        "confidence": conf,
        "details": details,
        "breakdown": breakdown,
        "timestamp": datetime.utcnow(),
    }

    res = history_collection.insert_one(doc)
    doc["_id"] = str(res.inserted_id)
    doc["timestamp"] = doc["timestamp"].isoformat()

    return {"result": doc}

# ================= HISTORY =================
@app.get("/history")
def get_history(current_user: dict = Depends(get_current_user)):
    docs = list(
        history_collection.find({"email": current_user["email"]}).sort("timestamp", -1)
    )
    for d in docs:
        d["_id"] = str(d["_id"])
        d["timestamp"] = d["timestamp"].isoformat()
    return {"history": docs}

@app.delete("/history/all")
def delete_all_history(current_user: dict = Depends(get_current_user)):
    history_collection.delete_many({"email": current_user["email"]})
    return {"success": True}

# ================= PDF DOWNLOAD =================
@app.get("/download-report/{report_id}")
def download_report(report_id: str, current_user: dict = Depends(get_current_user)):
    record = history_collection.find_one(
        {"_id": ObjectId(report_id), "email": current_user["email"]}
    )

    if not record:
        raise HTTPException(status_code=404, detail="Report not found")

    record["timestamp"] = record["timestamp"].isoformat()

    os.makedirs("reports", exist_ok=True)
    pdf_path = f"reports/fluency_report_{uuid.uuid4().hex}.pdf"

    generate_pdf_report(record, pdf_path)

    def cleanup():
        try:
            os.remove(pdf_path)
        except OSError:
            pass

    import threading
    threading.Timer(30, cleanup).start()

    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename="Fluency_Assist_Report.pdf",
    )

# ================= RUN =================
if __name__ == "__main__":
    uvicorn.run(
        "app:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )
